#!/usr/bin/env bash
# Create machine-local Jupyter password auth at ~/.secrets/jupyter_auth.py
# Loaded by stowed ~/.jupyter/jupyter_notebook_config.py — never committed.
# HUMAN: interactive getpass. Do not run from an unattended agent.
set -euo pipefail

export GUIX_PROFILE="${GUIX_PROFILE:-$HOME/.guix-profile}"
if [[ -r "$GUIX_PROFILE/etc/profile" ]]; then
  set +u
  # shellcheck disable=SC1091
  source "$GUIX_PROFILE/etc/profile"
  set -u
fi

SECRETS_DIR="${QIMONO_SECRETS_DIR:-$HOME/.secrets}"
AUTH_FILE="${SECRETS_DIR}/jupyter_auth.py"

if ! command -v jupyter-notebook >/dev/null 2>&1; then
  echo "error: jupyter-notebook not on PATH. Run scripts/apply-profile.sh first." >&2
  exit 1
fi

# Resolve Guix notebook Python + GUIX_PYTHONPATH (profile python3 is often 3.11
# without notebook on sys.path).
eval "$(
  python3 - <<'PY'
from pathlib import Path
import re, shutil, shlex

w = Path(shutil.which("jupyter-notebook") or "")
if not w.is_file():
    raise SystemExit("error: jupyter-notebook not found")
w = w.resolve()
text = w.read_text(encoding="utf-8", errors="replace")
m = re.search(r'export GUIX_PYTHONPATH="([^"]*)"', text)
if not m:
    raise SystemExit("error: GUIX_PYTHONPATH not found in jupyter-notebook wrapper")
gpp = m.group(1)

m2 = re.search(r'exec -a \S+ "([^"]+jupyter-notebook-real)"', text)
if not m2:
    raise SystemExit("error: could not locate .jupyter-notebook-real in wrapper")
real = Path(m2.group(1))
shebang = real.read_text(encoding="utf-8", errors="replace").splitlines()[0]
py = shebang[2:].split()[0]
print(f"export GUIX_PYTHONPATH={shlex.quote(gpp)}")
print(f"PY={shlex.quote(py)}")
PY
)"

if [[ -z "${PY:-}" || -z "${GUIX_PYTHONPATH:-}" ]]; then
  echo "error: failed to resolve notebook Python environment" >&2
  exit 1
fi

if ! "$PY" -c "from notebook.auth import passwd" 2>/dev/null; then
  echo "error: cannot import notebook.auth.passwd with $PY" >&2
  exit 1
fi

mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

if [[ -f "$AUTH_FILE" ]]; then
  echo "Existing auth file: $AUTH_FILE"
  read -r -p "Overwrite? [y/N] " ans
  case "${ans:-}" in
    y|Y|yes|YES) ;;
    *) echo "aborted."; exit 0 ;;
  esac
fi

echo "Set a Jupyter login password (not stored in plaintext; only a hash is written)."
HASH="$(
  "$PY" - <<'PY'
from getpass import getpass
from notebook.auth import passwd

p1 = getpass("Password: ")
p2 = getpass("Confirm password: ")
if not p1:
    raise SystemExit("error: empty password")
if p1 != p2:
    raise SystemExit("error: passwords do not match")
print(passwd(p1))
PY
)"

umask 077
cat >"$AUTH_FILE" <<EOF
# Machine-local Jupyter auth — DO NOT commit or stow.
# Generated by scripts/setup-jupyter-auth.sh on $(date -Iseconds)
# Loaded by ~/.jupyter/jupyter_notebook_config.py (stow package jupyter).

c.ServerApp.password = "${HASH}"
c.NotebookApp.password = c.ServerApp.password

# Password login: disable random tokens (avoids token leaks in journalctl)
c.ServerApp.token = ""
c.NotebookApp.token = ""
EOF
chmod 600 "$AUTH_FILE"

echo
echo "OK: wrote $AUTH_FILE (mode 600)"
echo "    passphrase: store in your password manager (not in git)"
echo "    hash only:  on disk above"

if command -v systemctl >/dev/null 2>&1 && systemctl --user cat qimono-jupyter.service >/dev/null 2>&1; then
  echo
  read -r -p "Restart qimono-jupyter.service now? [Y/n] " rs
  case "${rs:-Y}" in
    n|N|no|NO) echo "Restart later: systemctl --user restart qimono-jupyter.service" ;;
    *)
      systemctl --user daemon-reload || true
      systemctl --user restart qimono-jupyter.service
      echo "Restarted. Open http://127.0.0.1:5005 and log in with your password."
      ;;
  esac
else
  echo "Restart Jupyter when ready: systemctl --user restart qimono-jupyter.service"
fi
