#!/usr/bin/env bash
# Make the Guix flatpak's host-side D-Bus session services activatable.
#
# Why this exists:
#   Guix owns the flatpak CLIENT, so its helper daemons live in the profile,
#   NOT on the host. The package ships D-Bus activation files under
#     $GUIX_PROFILE/share/dbus-1/services/
#   but the systemd *user* manager's XDG_DATA_DIRS does not include the Guix
#   profile (10-guix.zsh only affects interactive shells), so dbus-daemon
#   never scans them. Result: names exist but nothing answers.
#
#   Symptom (Ghostty flatpak, 2026-08-21):
#     warning(glib): Unable to retrieve the Flatpak portal version:
#       org.freedesktop.portal.Flatpak was not provided by any .service files
#     warning(flatpak): Flatpak.HostCommand failed: … ServiceUnknown
#     warning(flatpak): error starting host command: error.FlatpakRPCFail
#     → sandboxed terminal cannot spawn its shell → app exits instantly;
#       GNOME tile "does nothing".
#
# Fix: write activation files into ~/.local/share/dbus-1/services/ — a dir
# dbus-daemon ALWAYS scans — pointing at the STABLE ~/.guix-profile/libexec
# symlinks, so they survive guix pull / upgrades / store GC.
#
# Idempotent. Safe to re-run. If the running bus cached its dir listing,
# log out/in once (same R1 discipline as the sysctl drop-in).
set -euo pipefail

DEST="${HOME}/.local/share/dbus-1/services"
LIBEXEC="${HOME}/.guix-profile/libexec"

write_service() {
  local name="$1" helper="$2"
  local exec_path="${LIBEXEC}/${helper}"
  local file="${DEST}/${name}.service"

  if [[ ! -x "$exec_path" ]]; then
    echo "error: missing $exec_path" >&2
    echo "       is 'flatpak' in the Guix profile? (guix/manifests/profile-full.scm)" >&2
    exit 1
  fi

  mkdir -p "$DEST"
  # NOTE: no SystemdService= line on purpose — those units do not exist on a
  # foreign distro; classic Exec activation is what we want.
  cat >"$file" <<EOF
# Generated by ubuntu-hp-pro/scripts/link-flatpak-host-services.sh
[D-BUS Service]
Name=${name}
Exec=${exec_path}
EOF
  chmod 644 "$file"
  echo "OK: ${file}"
  echo "    Name=${name}"
  echo "    Exec=${exec_path}"
}

echo "==> linking Guix flatpak host services into ${DEST}"

# 1) Session helper — spawns processes on the HOST for sandboxed apps.
#    Required by terminal emulators (ghostty): Flatpak.HostCommand / Spawn.
write_service org.freedesktop.Flatpak flatpak-session-helper

# 2) Flatpak portal alias — modern xdg-desktop-portal no longer registers
#    this name; flatpak-portal provides it (portal version queries, updates).
write_service org.freedesktop.portal.Flatpak flatpak-portal

# 3) App activation files (DBusActivatable=true apps are launched by GNOME
#    via D-BUS NAME, never via the .desktop Exec). Flatpak exports them under
#    exports/share/dbus-1/services/, which the systemd-user session bus cannot
#    scan (same XDG_DATA_DIRS gap as above) → tile clicks do nothing, silently.
#    The exported Exec lines already use stable $HOME/.guix-profile paths, so a
#    plain symlink survives guix pull / upgrades / app updates.
EXPORTS_DBUS="${HOME}/.local/share/flatpak/exports/share/dbus-1/services"
if [[ -d "$EXPORTS_DBUS" ]]; then
  mkdir -p "$DEST"
  find "$EXPORTS_DBUS" -maxdepth 1 -name '*.service' -print0 |
    while IFS= read -r -d '' src; do
      dst="${DEST}/$(basename "$src")"
      if [[ "$(readlink "$dst" 2>/dev/null)" == "$src" ]]; then
        echo "OK: ${dst} (already linked)"
      else
        ln -sfn "$src" "$dst"
        echo "OK: ${dst} → ${src}"
      fi
    done
fi

echo
echo "Done. Test:"
echo "  ghostty +version            # CLI via stow shim (~/.local/bin/ghostty)"
echo "  flatpak run com.mitchellh.ghostty   # GUI; window must stay open with a shell"
echo "If the tile still does nothing: log out/in once so dbus rescans service dirs."
